### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by sergey-shaldanov** [SpiderLabs/cribdrag#1]
> REQUIREMENTS
> python 3.2+

Really? Seems like, required version 2.X+.

**Comment by tomarrell** [comment]
Yea it would make no sense to use and 3.X version as a quick scan of the source code sees it uses print "text" without brackets and raw_input to take input, both being 2.X methods of doing so.

**Comment by unicornsasfuel** [comment]
This is an incredibly silly thing to nitpick about, especially after the issue was raised and ignored almost a year ago, but it's fixed now regardless.

**Comment by tomarrell** [comment]
I don't believe listing an incompatible version of Python to successfully build your program to be an "incredibly silly" thing to get right. Might save unknowing people an hour or so down the line. 

Regardless, I've ported it to 3.X+ if you would like me to make a pull request.

**Comment by unicornsasfuel** [comment]
No, this is a silly issue on par with a typo. Nobody is going to spend an hour figuring out that they need to run under python2 instead of python3. It likely didn't even take you an hour to port it to 3.x. Thank you for the offer of a pull request, but if you insist on my work being Python3 compatible, please do so in your own fork.

This issue is fixed and closed, there is no reason to discuss it further. As such, I am locking the conversation.
